name: Build and Release Docker Image

on:
  push:
     branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-22.0.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 构建或拉取 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t kafka:latest .
      
      # 保存 Docker 镜像为 tar 文件
      - name: Save Docker Image as tar
        run: |
          docker save -o ./kafka.tar kafka:latest
      
      # 创建 GitHub 发布版本
      - name: Pull Image release
        run: docker pull wurstmeister/kafka
