name: Docker Image Download

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Download Docker image
        run:  docker pull  wurstmeister/kafka
